Repository SwitchDreams/mw-melhorado-front, pull requests merged in 2020-07, with the labels that each got.

#5 Adicionando estrutura básica do Front + início da página de curso.
  .eslintrc.json
  package-lock.json
  package.json
  src/components/Header/styles.ts
  src/pages/Course/index.tsx
  src/pages/Course/styles.ts
  src/pages/Dashboard/index.tsx
  src/styles/global.ts
  yarn.lock
Labels: Front, good first issue

#11 Conectando com API.
  .eslintrc.json
  src/pages/Course/index.tsx
  src/pages/Course/styles.ts
Labels: Front

#19 Landing page
  public/index.html
  src/App.tsx
  src/assets/unb_antiga.jpg
  src/components/FeatureCard/index.tsx
  src/components/FeatureCard/styles.ts
  src/components/Footer/index.tsx
  src/components/Footer/styles.ts
  src/components/Header/index.tsx
  src/components/Header/styles.ts
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/styles.ts
  src/styles/global.ts
Labels: Front

#23 Refatorando list courses
  .eslintrc.json
  src/assets/spinner-icon.gif
  src/pages/ListCourses/index.tsx
  src/pages/ListCourses/styles.ts
Labels: Front, enhancement

#24 Adding selected subject card.
  src/pages/Course/index.tsx
  src/pages/Course/styles.ts
Labels: Front

#30 Refactoring code.
  .eslintrc.json
  src/components/SubjectCard/index.tsx
  src/components/SubjectCard/styles.ts
  src/pages/Course/flux.tsx
  src/pages/Course/index.tsx
  src/pages/Course/infoCards.tsx
  src/pages/Course/styles.ts
Labels: Front, M

#31 Melhorar Responsividade.
  src/pages/Course/flux.tsx
  src/pages/Course/index.tsx
  src/pages/Course/styles.ts
Labels: Front, M

#32 Ondinha na navbar e no footer.
  src/components/Footer/index.tsx
  src/components/Footer/styles.ts
  src/components/Header/index.tsx
  src/components/Header/styles.ts
  src/pages/Course/index.tsx
  src/pages/Course/styles.ts
  src/pages/Dashboard/index.tsx
  src/pages/ListCourses/index.tsx
Labels: Front, M
