Repository SwitchDreams/mw-melhorado-front, pull requests merged in 2020-08, with the labels that each got.

#33 Toast
  package.json
  src/App.tsx
  src/components/ToastContainer/Toast/index.tsx
  src/components/ToastContainer/Toast/styles.ts
  src/components/ToastContainer/index.tsx
  src/components/ToastContainer/styles.ts
  src/hooks/toasts.tsx
  src/pages/ListCourses/index.tsx
  src/pages/ListCourses/styles.ts
Labels: Front, enhancement

#36 Página da Disciplina.
  package.json
  src/assets/canvasjs.min.js
  src/assets/canvasjs.react.js
  src/components/Header/index.tsx
  src/components/Loading/index.tsx
  src/components/Loading/styles.ts
  src/pages/Course/flux.tsx
  src/pages/Course/index.tsx
  src/pages/Course/styles.ts
  src/pages/ListCourses/index.tsx
  src/pages/ListCourses/styles.ts
  src/pages/Subject/graphic.tsx
  src/pages/Subject/index.tsx
  src/pages/Subject/styles.ts
  src/routes/index.tsx
  yarn.lock
Labels: Front, L

#41 Responsive navbar
  package.json
  src/App.tsx
  src/components/Header/index.tsx
  src/components/Header/styles.ts
Labels: Front, enhancement

#42 Merge final sprint 2
  package-lock.json
  package.json
  src/pages/Course/index.tsx
Labels: Front

#47 Mostrar as equivalências na página da disciplina.
  src/App.tsx
  src/pages/Course/styles.ts
  src/pages/Subject/equivalence.tsx
  src/pages/Subject/graphic.tsx
  src/pages/Subject/index.tsx
  src/pages/Subject/prereq.tsx
  src/pages/Subject/styles.ts
  src/styles/global.ts
Labels: Front, L

#57 Improvements landing page
  src/assets/cloudy-sd.svg
  src/assets/perfil_bahia.jpeg
  src/assets/perfil_bruna.png
  src/assets/perfil_japa.jpeg
  src/assets/perfil_pedro.jpeg
  src/assets/perfil_waliff.png
  src/components/FeatureCard/index.tsx
  src/components/FeatureCard/styles.ts
  src/components/Header/index.tsx
  src/pages/ContactUs/index.tsx
  src/pages/ContactUs/styles.ts
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/styles.ts
  src/pages/ListCourses/styles.ts
  src/pages/Subject/styles.ts
  src/routes/index.tsx
Labels: Front, enhancement
